name: fera-api bump version

env:
  NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

on:
 workflow_dispatch:
 pull_request_target:
    branches: [ main, release** ]
    types:
      - closed

jobs:
  echo-var:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.base_ref }}
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.event_name }}
    - run: echo ${{ github.event.action }}
    - run: echo ${{ github.event.pull_request.merged }}

  bump-version:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - shell: bash
      run: |
        echo "Cleaning workspace directory..."
        sudo rm -rfv ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}
          
    - uses: actions/checkout@v3
    - name: bump assembly patch version
      if: github.ref == 'refs/heads/main'
      run: echo "ouch"

    - name: commit files
      run: |
          date > generated.txt
          git config user.email github-actions@github.com
          git config user.name "github-actions"
          #git remote set-url origin https://x-access-token:${{secrets.github_token}}@github.maybank.com/${{github.repository}}
          git commit -m "bump build version" -a
          git push